# image: jhipster/jhipster:v7.9.3
image: python:3.7.16

variables:
  CI_IMG: "\"${CI_REGISTRY_IMAGE}:latest\""
  TP_URL: "${CI_PROJECT_NAMESPACE}.bham.team"
  TP_CONTACT: "${GITLAB_USER_EMAIL}"
cache:
  key: '$CI_COMMIT_REF_NAME'
  # paths:
  #   - .maven/
stages:
  - check
  # - build
  - test
  # - analyze
  # - package
  # - release
  - publish
  - deploy
# before_script:
  # - export NG_CLI_ANALYTICS="false"
  # - export MAVEN_USER_HOME=`pwd`/.maven

prerequisities:
  image: python:3.7.16
  stage: check
  # only:
  #   - main
  script:
    - pip install -r requirements.txt
    - python mySite/mysite/manage.py check


django-test:
  image: python:3.7.16
  stage: test
  # only:
  #   - main
  script:
    - pip install -r requirements.txt
    - python mySite/mysite/manage.py test
# nohttp:
#   stage: check
#   script:
#     - ./mvnw -ntp checkstyle:check -Dmaven.repo.local=$MAVEN_USER_HOME

# maven-compile:
#   stage: build
#   script:
#     - ./mvnw -ntp compile -P-webapp -Dmaven.repo.local=$MAVEN_USER_HOME
#   artifacts:
#     paths:
#       - target/classes/
#       - target/generated-sources/
#     expire_in: 1 day

# maven-package:
#   stage: package
#   script:
#     - echo "jhipster" | sudo -S apt-get update
#     - echo "jhipster" | sudo -S apt-get install -y chromium-browser
#     - echo `whereis chromium-browser`
#     - ./mvnw -ntp verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
#   artifacts:
#     paths:
#       - target/*.jar
#       - target/classes
#     expire_in: 1 day

publish-docker:
  image: docker:stable
  stage: publish
  
  # only:
  #   - main
  services:
    - docker:dind
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "pushing ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_USER} ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:tpdjango mySite/
    - docker push ${CI_REGISTRY_IMAGE}:tpdjango
    - docker build -t ${CI_REGISTRY_IMAGE}:tpnginx nginx/
    - docker push ${CI_REGISTRY_IMAGE}:tpnginx
    - docker container ls -a >> file.txt
    - cat file.txt
#uncomment this once the $RSA $VM_USER@$VM are set in the repo - Setting -> CI/CD -> variables
#$RSA should be a private key file, $VM_USER is the VM user name (e.g. root or ec2) and $VM is the IP address of the Virtual Machine
#this assumes docker and SSH is installed on the $VM


# deploy-git:
#   image: alpine:latest
#   stage: deploy
#   # only:
#   #   - main
#   when: on_success
#   before_script:
#     - chmod og= $RSA
#     - apk update && apk add openssh-client
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker stop tpdjango || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker stop tpnginx || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker rm tpdjango || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker rm tpnginx || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "rm -rf ~/team-project-deployment || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker container ls -a"
#     # - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d --name docker-teamproject-app-1 git.cs.bham.ac.uk:5050/team-projects-2022-23/team22-22:latest"
#     # - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker stop fc1976f6c6a2"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpdjango"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpnginx"
#   script:
#     - scp -o StrictHostKeyChecking=no -i $RSA -r . $VM_USER@$VM:~/team-project-deployment
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 8000:8000 --name tpdjango --network-alias tpdjango ${CI_REGISTRY_IMAGE}:tpdjango"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 80:80 --name tpnginx --link tpdjango:tpdjango --network-alias tpnginx ${CI_REGISTRY_IMAGE}:tpnginx"



# deploy-git:
#   image: alpine:latest
#   stage: deploy
#   when: on_success
#   before_script:
#     - chmod og= $RSA
#     - apk update && apk add openssh-client
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker stop tpdjango || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker stop tpnginx || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker rm tpdjango || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker rm tpnginx || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "rm -rf ~/team-project-deployment || true"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker container ls -a"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpdjango"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpnginx"
#   script:
#     - scp -o StrictHostKeyChecking=no -i $RSA -r . $VM_USER@$VM:~/team-project-deployment
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker network create tpnetwork"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 8000:8000 --name tpdjango --network tpnetwork --network-alias tpdjango ${CI_REGISTRY_IMAGE}:tpdjango"
#     - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 80:80 --name tpnginx --network tpnetwork --network-alias tpnginx ${CI_REGISTRY_IMAGE}:tpnginx"


deploy-git:
  image: alpine:latest
  stage: deploy
  when: on_success
  before_script:
    - apk update && apk add openssh-client
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker network rm tpnetwork || true"
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker network create tpnetwork"
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpdjango"
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker pull ${CI_REGISTRY_IMAGE}:tpnginx"
  script:
    - scp -o StrictHostKeyChecking=no -i $RSA -r . $VM_USER@$VM:~/team-project-deployment
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 8000:8000 --name tpdjango --network tpnetwork ${CI_REGISTRY_IMAGE}:tpdjango"
    - ssh -o StrictHostKeyChecking=no -i $RSA $VM_USER@$VM "docker run -d -p 80:80 --name tpnginx --network tpnetwork ${CI_REGISTRY_IMAGE}:tpnginx"


